#!/bin/bash

#compile all programs using c99 standard

gcc -g -o keygen keygen.c

gcc -g -o enc_server enc_server.c

gcc -g -o enc_client enc_client.c

gcc -g -o dec_server dec_server.c

gcc -g -o dec_client dec_client.c

